In [1]:
import pandas as pd

In [3]:
paragraphs_df = pd.read_csv('../csvs/labels_per_paragraph.csv')

In [4]:
hard_252 = '''We don’t make more money today as land developers. We make far less with some of us getting into the home construction business and building ourselves since land profit has evaporated.

Blame red tape, environmental “protection”, and slow procedures to develop land as the reason for astronomical housing prices.

If you want the government to intervene to make housing more affordable, then must invest in housing themselves, not placing rental caps as price caps have failed just about every time in history.

Most politicians in my province (and probably federally) are also landlords with an incentive to do nothing meaningful to resolve the housing crisis. They also tend to love the infusion of foreign capital the housing crunch brings.

The incentive is to court middle-class home owners using their advantage of having bought decades ago. This group does not benefit from meaningful attempts to correct the problem, so anything that would actually help is off-limits.

Obviously nobody on the centre-right is particularly inclined to significant change to help the poor. More surprisingly they have no interest in meaningfully dealing with foreign home ownership either. Nobody in the centre is inclined to decrease one of the world's highest per capita immigration rates (something they just increased again), and nobody on the centre-left wants to deal with the immigration boom either or meaningfully deal with foreign home ownership either. They consider it a dogwhistle.'''

In [6]:
hard_252 = hard_252.split('\n\n')

In [11]:
paragraphs_df

,text-id,text,label,version
0,medium-17,"Due to the overreach on the initial layoffs, c...",1,3
1,medium-17,I used to be in Pharmacy. Then I did a researc...,0,3
2,medium-17,So if a medical center has any that are partia...,1,3
3,medium-17,Open vials are supposed to be discarded after ...,1,3
4,medium-17,It costs about 15-35 cents to make a mL of ins...,1,3
...,...,...,...,...
161,hard-862,"Well, I still don’t have an answer. I have opt...",0,6
162,hard-862,"Same here, others too. I don’t consider email ...",1,6
163,hard-862,After months of email going to spam I finally ...,1,6
164,hard-862,Receiving the same e-mails from Cedars trying ...,0,6
165,hard-862,So according to customer support of the compan...,1,6

In [13]:
label = [0, 1, 1, 0, 0]
data = []

for (p1, p2), y in zip(zip(hard_252, hard_252[1: ]), label):
    p1 = p1.strip()
    p2 = p2.strip()

    data.append({'text-id': 'hard-252', 'text': p1 + '\n' + p2, 'label': y, 'version': -1})

hard_252_df = pd.DataFrame(data)

In [14]:
hard_252_df

    text-id                                               text  label  version
0  hard-252  We don’t make more money today as land develop...      0       -1
1  hard-252  Blame red tape, environmental “protection”, an...      1       -1
2  hard-252  If you want the government to intervene to mak...      1       -1
3  hard-252  Most politicians in my province (and probably ...      0       -1
4  hard-252  The incentive is to court middle-class home ow...      0       -1

In [19]:
all_paragraphs = pd.concat([paragraphs_df, hard_252_df], axis=0)

In [23]:
all_paragraphs

,text-id,text,label,version
0,medium-17,"Due to the overreach on the initial layoffs, c...",1,3
1,medium-17,I used to be in Pharmacy. Then I did a researc...,0,3
2,medium-17,So if a medical center has any that are partia...,1,3
3,medium-17,Open vials are supposed to be discarded after ...,1,3
4,medium-17,It costs about 15-35 cents to make a mL of ins...,1,3
...,...,...,...,...
0,hard-252,We don’t make more money today as land develop...,0,-1
1,hard-252,"Blame red tape, environmental “protection”, an...",1,-1
2,hard-252,If you want the government to intervene to mak...,1,-1
3,hard-252,Most politicians in my province (and probably ...,0,-1
4,hard-252,The incentive is to court middle-class home ow...,0,-1

In [24]:
all_paragraphs.to_csv('all_paragraphs.csv', index=False)